### ISSUE TITLE
The title of the document needs to be more than one (commonly used) word

### ISSUE THREAD

**Issue by dwsinger** [whatwg/encoding#11]
'Encoding' is used all over our discipline: of audio, video, images, and all sorts of transformations. The title tells us close to nothing of what this is about.

Please can we have a slightly more descriptive title (at least 'Text' included, and maybe the fact that this deals with the conversion and normalization of text)?

**Comment by duerst** [comment]
Just as a strawman, I propose something like "Character Encodings for the Web Platform"

**Comment by annevk** [comment]
I discussed this with some others in the community and we're not going to change this as:

1. It's disruptive.
2. It hasn't really caused any confusion thus far.
3. It would be inconsistent with how the WHATWG names standards.
4. The current name is rather cool.

**Comment by nigelmegitt** [comment]
I support the view that the current title is an issue and that it would be better to change it. In response to the arguments for not changing:

1. The least disruptive moment to change it is "as soon as possible".
2. It has already caused confusion otherwise the issue wouldn't have been raised.
3. and 4. Consistency and coolness must come secondary to usefulness. Encoding is an unhelpful name for the reasons described. A good name for a spec is one that either has an existing strong brand that is not orthogonal to the contents or that describes what is in the spec in a useful shorthand. "Encoding" doesn't do either.

**Comment by domenic** [comment]
@nigelmett can you give links to this observed confusion? Note that we're not worried about causing confusion to drive-by reviewers, but instead substantive cases like someone writing a video processing spec and accidentally referencing the Encoding Standard because they thought it would contain algorithms for H264.

**Comment by nigelmegitt** [comment]
@domenic no I can't give any links! However I agree that you should avoid the potential referencing confusion and be specific about the kinds of content for which the "Encoding" standard actually defines the encoding. WHATWG itself does not provide enough context to understand it since the scope of WHATWG's activities is broad.

**Comment by domenic** [comment]
The lack of links is what we meant by 2.

**Comment by nigelmegitt** [comment]
You're setting the bar very high here for what I'd consider a matter of common sense.

**Comment by dwsinger** [comment]
I think we want people to be aware of this spec and what it’s about, if they see it referenced, if they see its title somewhere, if they see a ‘request for review’ and so on. The title should be good enough to alert people that they might be interested, might need to read and use it, should review it, and so on.

I really think that helpful is better than ‘cool’ (and cool is in the eye of the beholder).

We’re not writing specs for ourselves, we’re writing specs to try to help the entire industry.

> On Nov 9, 2015, at 9:58 , Domenic Denicola <notifications@github.com> wrote:
> 
> @nigelmett can you give links to this observed confusion? Note that we're not worried about causing confusion to drive-by reviewers, but instead substantive cases like someone writing a video processing spec and accidentally referencing the Encoding Standard because they thought it would contain algorithms for H264.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

David Singer
Manager, Software Standards, Apple Inc.
