### ISSUE TITLE
For your information: Illegal UTF-8 proposal

### ISSUE THREAD

**Issue by peteroupc** [whatwg/encoding#112]
For your information. I've recently become aware of the following proposal, by Markus Scherer, that deals with the recommended way to handle invalid UTF-8.  It was recently uploaded to the Unicode Web site and I believe it may be relevant to the Encoding Standard:

http://www.unicode.org/L2/L2017/17168-utf-8-recommend.pdf

Note that this is merely a proposal; and I have no opinion on whether the Encoding Standard should adopt this proposal if it's adopted by the Unicode Technical Committee and/or incorporated into a future version of the Unicode Standard.

**Comment by hsivonen** [comment]
Thank you for pointing to this. If adopted, this would differ from the Encoding Standard. What makes more sense depends on implementation strategy. I'm not particularly happy about Unicode switching from their spec text to ICU bugwards compat after Firefox (both old and new code) believed the spec text they had.

**Comment by hsivonen** [comment]
[I started a thread on the unicode mailing list.](http://unicode.org/pipermail/unicode/2017-May/005389.html)

(In retrospect, I should have made the initial message less combative.)

**Comment by annevk** [comment]
It seems this proposal has been adopted for Unicode 11, but can still be appealed for the next nine months or so.

The expected outcome if it cannot be appealed is that we end up going against the Unicode recommendation since it doesn't seem worth it to change a decade-long agreement over arguments that mostly come down to it being convenient for ICU (and go somewhat against an earlier UTF-8 design decision of limiting itself to four bytes). That does mean we need to add plenty of tests to all the places where UTF-8 ends up being web-exposed (and reference this standard) as otherwise the ecosystem might subtly regress in stability over time due to conflicting recommendations.

**Comment by annevk** [comment]
@peteroupc thank you for bringing this to our attention. It seems the matter has been resolved and no changes are needed anywhere: http://unicode.org/pipermail/unicode/2017-August/005686.html.

If anyone would like to read a detailed summary I can recommend https://hsivonen.fi/broken-utf-8/.
