### ISSUE TITLE
UTf7 supports

### ISSUE THREAD

**Issue by lygstate** [whatwg/encoding#16]
UTf7 are used in email files, so add it in encoding as default, or provide way to add extensions for support other encodings

**Comment by hsivonen** [comment]
I think this should be closed as "won't fix", because this is a Web-oriented spec and not an email-oriented spec.

It does follow that if you are implementing an email client that performs MIME decoding in JavaScript running on a browser engine, you have to implement an UTF-7 decoder in JS instead of calling into a browser-provided facility like `TextDecoder`. That's somewhat unfortunate, but the alternative would be speccing UTF-7 as a special encoding that's exposed only via `TextDecoder` and not in other places where the Web Platform exposes decoder.

But then, JS email app developers need to implement the IMAP variant of UTF-7 in JS anyway. (Unless you are arguing that the spec should support that encoding, too, and even on the `TextEncoder` side.)

**Comment by annevk** [comment]
Agreed. If this becomes a big problem we can reconsider, but implementing your own special purpose encoding support in JavaScript is not that hard.
