### ISSUE TITLE
TextDecoderStream: empty Uint8Array should result in an empty string

### ISSUE THREAD

**Issue by crowlKats** [whatwg/encoding#283]
Currently the [specification states](https://encoding.spec.whatwg.org/#decode-and-enqueue-a-chunk
):
> If outputChunk is non-empty, then enqueue outputChunk in decoder’s transform.

Lets say I have a Uint8Array based transform stream that splits by line, and we have an empty line (which means the transformstream will queue an empty Uint8Array), TextDecoderStream will make that empty line disappear into thin air, which is not great.

This argument also goes for TextEncoderStream discarding an empty Uint8Array.

**Comment by MattiasBuelens** [comment]
I think this is intentional. Readable byte streams also don't allow writing empty chunks, and it's likely that we'll want to make `TextDecoderStream.readable` a proper byte stream in the future:
```javascript
const rs = new ReadableStream({
  type: "bytes",
  start(controller) {
    controller.enqueue(new Uint8Array(0)); // throws
  }
});
```
I'm a bit surprised by Deno's `LineStream` design. I would expect a transform stream that splits text by line delimiters would accept *strings* as input and produce *strings* as output. Instead, it looks like it uses raw byte chunks as both input and output?

That means that `LineStream` is making an assumption about the text encoding, right? How exactly is that supposed to deal with multi-byte text encodings like `utf-16`? For example:
```javascript
new TextDecoder("utf-16").decode(new Uint8Array([0x41, 0x00, 0x0A, 0x00, 0x42, 0x00]));
// -> "A\nB"
```
I would expect you *first* run these chunks through a `TextDecoderStream`, and *then* split by line delimiters:
```javascript
const readable = new ReadableStream({
  start(controller) {
    controller.enqueue(new Uint8Array([0x41, 0x00, 0x0A, 0x00, 0x42, 0x00]));
    controller.close();
  }
});

readable
  .pipeThrough(new TextDecoderStream("utf-16"))
  .pipeThrough(new LineStream());
// -> stream with chunks "A" and "B"
```

**Comment by crowlKats** [comment]
I agree with the byte stream, that definitively would be great. I didn't take that concept into consideration when opening this issue, and as such I guess this issue is redundant.
One reason for `LineStream` to be `Uint8array` based was to align with a utility we have that does the equivalent but with Deno's `Deno.Reader` & `Deno.Writer`: so to have a 1-to-1 mapping & people effortlessly change over to the WHATWG streams based one; but looking back on it with this issue in mind, I see that might have been a mistake.
