### ISSUE TITLE
index-jis0208.txt should be JIS X 0208 and add another index file

### ISSUE THREAD

**Issue by takahashim** [whatwg/encoding#47]
The CCS(coded character set) of index-jis0208.txt is CCS of "CP932" or "Windows-31J".  It is not JIS X 0208.
There are two differences:
- CP932 has more characters than JIS X 0208.
- All CCS in JIS X 0208 has its name, for mapping to UCS.  There are some difference between it and index-jis0208.txt.

The important role of JIS X 0208 is restriction of character set.  For example, some fonts in Japan have characters only in JIS X 0208, not CP932.  So we need a strict character set to implement converter like Shift_JIS encoder.  We need another index which is differ from index-jis0208.txt.

Another usecase: sometimes I want to convert Shift_JIS text into EPUB file. It's typical usecase of Shift_JIS decoder.  When I do it, I want to convert EM DASH in Shift_JIS (0x815C, 1-1-29) to EM DASH in Unicode (U+2014).  It's OK in JIS X 0208 (and JIS X 0213), but It's NG in CP932; the table of index-jis0208.txt maps EM DASH into HORIZONTAL BAR(U+2015).  It's not what I want to do.

So my suggestions is:
- index-jis0208.txt should be renamed, such as index-cp932 or index-windows31j,
- and should add another index same as JIS X 0208.

I have machine-readable mapping table, "JIS X 0213:2004 8-bit code vs Unicode mapping table"
http://x0213.org/codetable/jisx0213-2004-8bit-std.txt. But It's JIS X 0213, not JIS X 0208.
I found the issue #31 and I also don't have a real usecase of SHIFT_JISX0213 nor Shift_JIS-2004 (when I want to use characters in JIS X 0213, I always use UTF-8).  I need just only JIS X 0208, subset of jisx0213-2004-8bit-std.txt.

**Comment by annevk** [comment]
The goal of this standard is to match browsers and similar clients, since they're the most dominant internet clients out there and whatever they do spreads elsewhere. Given that, I'm not sure such a change makes sense.

Also, if you're worried about fonts it would make sense to check the code points of the font against the code points you are looking to encode. I'm not sure how it makes sense to rely on the encoder.

**Comment by vyv03354** [comment]
It would make sense to rename the current file to index-windows-932.txt because it will clarify what browsers and similar clients actually use. ("cp932" is ambiguous because IBM and Microsoft have different "cp932" definitions.) But I disagree any non-utf8 additions.

**Comment by hsivonen** [comment]
I'd be OK with renaming the index to be more suggestive of Windows instead of JIS (editorial change), but I'm not OK with adding encoding variants that the major browsers don't already support (as that would be a substantive change and scope creep).

**Comment by jungshik** [comment]
I fully agree  with @hsivonen and @vyv03354.

**Comment by bhaible** [comment]
I vote for splitting the table index-jis0208.txt into two parts, one for the indices < 8836 (the actual JIS X 0208 matrix) and one for the indices >= 8836 (the CP932 additions by Microsoft). Reasons:
- JIS X 0208 is a CCS based on rows and columns, with 94 rows and 94 columns.
- The description in section 6 "This is the JIS X 0208 standard including formerly proprietary extensions from IBM and NEC." is inaccurate.
- The part with indices >= 8836 is only meant to be used in the Shift_JIS and (possibly) ISO-2022-JP conversions, not in the EUC-JP conversion.
- In fact, it causes a bug in the EUC-JP encoder: When the input code-point is e.g. 0x2170, the EUC-JP encoder will set 'lead = 275' and 'trail = 161', thus attempt to return a byte with value > 255 ! Some implementations will just operate mod 256 and return the byte sequence 0x13 0xA1.

**Comment by annevk** [comment]
@bhaible wow, I'm surprised nobody noticed the EUC-JP encoder bug yet. We could also fix that by returning error if the index is > 8835. That seems a lot safer than changing how lookup works across three encodings.

What exactly is inaccurate about the description in section 6?

**Comment by hsivonen** [comment]
@bhaible Great find! Thank you for spotting a bug.

As an editorial matter, the index doesn't need to be split in the JSON file in order to use only a part of the index in some context. There's already precedent for [subsetting an index upon lookup](https://encoding.spec.whatwg.org/#index-big5-pointer) in the Big5 encoder.

**Comment by vyv03354** [comment]
Does the the EUC-JP encoder really has the bug?
The step 7 for the EUC-JP encoder is defined as follows:

> Let pointer be the index pointer for code point in index jis0208. 

And "index pointer for code point" is defined as follows:

> The index pointer for code point in index is the *first* pointer corresponding to code point in index, or null if code point is not in index. 

So, for example, the index pointer for code point 0x2170 is 8634, not 10716. The the EUC-JP encoder will set 'lead = 252' and 'trail = 241'.

If some implementations set a lead >= 256, it's just a implementation bug.

**Comment by vyv03354** [comment]
> I vote for splitting the table index-jis0208.txt into two parts, one for the indices < 8836 (the actual JIS X 0208 matrix) and one for the indices >= 8836 (the CP932 additions by Microsoft).

I don't think it makes sense because windows-932 extensions are not simple additions to indices >= 8836. Indices < 8836 contain not only genuine JIS X 0208 characters but also NEC special characters and NEC selection of IBM extensions. Moreover, some windows-932 mappings are incompatible with genuine JIS X 0208 mappings. For example, windows-932 will map index 32 to U+FF5E while JIS X 0208 will map it to U+301C. It will only complicate things to split the index file into two parts.

**Comment by bhaible** [comment]
> So, for example, the index pointer for code point 0x2170 is 8634, not 10716. Then the EUC-JP encoder will set 'lead = 252' and 'trail = 241'.

Ah, in fact that happens to be true for all indices >= 8836. Sorry, that wasn't obvious to me. So, there is no bug.

How about adding a comment/note in EUC-JP decoder, step 7: "Note: If pointer is non-null, it is necessarily < 8836, due to the nature of the table."

Likewise in ISO-2022-JP encoder, step 9: "Note: If pointer is non-null, it is necessarily < 8836, due to the nature of the table."

Such comments would translate into an assertion when implementors translate the algorithm into a particular implementation language.

**Comment by annevk** [comment]
Yeah, that sounds reasonable.

**Comment by vyv03354** [comment]
> How about adding a comment/note in EUC-JP decoder, step 7: "Note: If pointer is non-null, it is necessarily < 8836, due to the nature of the table."

That's a good idea, given that some implementations failed to read the spec.

**Comment by annevk** [comment]
I created a PR for adding the notes. 

I'm not really convinced about the renaming effort. If we renamed this index we'd also have to rename index EUC-KR to index Windows-949 or some such and it's not really clear to me that's worth the effort. And e.g., with Big5 it would never be identical.

I'd rather improve the notes surrounding these indexes and not move resources around.

**Comment by annevk** [comment]
Closing this given the lack of follow-up to the points I made above.
