### ISSUE TITLE
"In equations, all numbers are integers, additio..."

### ISSUE THREAD

**Issue by ricea** [whatwg/encoding#66]
https://encoding.spec.whatwg.org/#terminology

> In equations, all numbers are integers, addition is represented by "+", subtraction by "−", multiplication by "×", division by "/", calculating the remainder of a division (also known as modulo) by "%", logical left shifts by "&lt;&lt;", logical right shifts by "&gt;&gt;", bitwise AND by "&amp;", and bitwise OR by "|". floor(x) is the largest integer not greater than x.

"all numbers are integers" contradicts "floor(x) is the largest integer not greater than x". To be more specific, it implies that x is an integer and therefore floor(x) is a no-op.

I suggest defining "/" as integer division and dropping all mentions of floor() from the spec. floor(pointer / 10 / 126 / 10) should be changed to pointer / (10 \* 126 \* 10) to avoid loss of precision, and similarly with floor(pointer / 10 / 126).

**Comment by annevk** [comment]
Yeah, that is what we had before. However, in #20 (and also somewhere else, earlier) folks requested a more explicit notation.

Paging @domenic and @r12a.

**Comment by domenic** [comment]
I guess part of what's unclear is whether "all numbers are integers" means "all inputs are integers" or "all operations are integer operations." And if the latter, it's not obvious what "division" means (thus #20).

I guess I would fix this by getting rid of "all numbers are integers". But it would also be OK to fix it by saying "all numbers (including both inputs and intermediate results) are integers" and adding "division here is defined by the result of taking the floor after performing mathematical division on the input integers" or something.

**Comment by ricea** [comment]
I think "all inputs are integers" would describe the status quo succinctly. This hopefully means that implementers will get it right even if they skip the terminology section.

If precision is better than succinctness, then "All inputs and outputs are integer. Division is considered to produce an infinite-precision intermediate result which is always converted to an integer using the floor() operation. In practice, integer division is expected to be used where available."

**Comment by r12a** [comment]
My 2p: Personally i prefer to make it as clear as possible what is meant at the point where the reader of the spec is looking (rather than hoping that they read a statement elsewhere) for this kind of thing. I agree that 'all numbers are integers' is slightly misleading, and prefer something like ''All inputs and outputs are integers." for the general description, but i would personally prefer to keep the equation complete (ie. keep the floor).

I'd be happy to see the equation changed to floor(pointer (10 * 126 * 10)) to avoid loss of precision.  

I don't see an advantage in removing parts of the equation, and i don't see any inconvenience in adding a couple of extra brackets.

hth

**Comment by annevk** [comment]
@r12a in #65 I have tried to clarify the math, review of that would be appreciated. Once that is reviewed and landed I think I'll take the suggestion from @ricea above and clarify that integer division is expected to be used, but that we use floor() for clarity and languages where that might not be available.

**Comment by ricea** [comment]
On further reflection, my comment about expressions like (pointer / 10 / 126 / 10) losing precision was incorrect. Please disregard that part.

**Comment by annevk** [comment]
The main reason I'm changing those expressions is on request of @hsivonen. I suspect compilers can more easily deal with the multiplications. The math should be okay either way indeed.

**Comment by hsivonen** [comment]
The reason isn't that compilers can more easily deal with multiplications. The reason why I asked for that change is three-fold:

1. Even when two expressions involving one variable and a bunch of constants are equivalent in abstract infinite-precision math or in two's complement math without under/overflow checking, the order in which operations may be significant when under/overflow checking is involved. The sure way not to introduce badness from repetitive under/overflow checking is to make sure that all the operations that can be performed on the constants only are grouped together so that those operations can be folded ahead of time.
2. It's clearer for the reader to see that there is, indeed, the same folded constant repeating if it appears as the same parenthetized multiplication both times instead of masquerading as a bunch of divisions.
3. When the same operands appear both with `/` and `%`, this makes it clear (to humans and hopefully computers) that an operation that outputs both the quotient and the remainder in one go.

I think the spec should get rid of the "floor()" notation and instead define `/` as an integer division operator that performs division on two integers, returns the quotient and discards the remainder.

**Comment by annevk** [comment]
#100 removes floor(). Review appreciated.
