### ISSUE TITLE
Important warnings getting lost in the noise

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#97]
I was afraid of this. Look at the output of https://travis-ci.org/whatwg/encoding/builds/204200335 and try to spot the problem. It's #95.

@sideshowbarker how hard is it to make it possible to configure warnings? Alternatively, maybe we can instrument separate runs for index.html and the other resources whereby index.html doesn't tolerate warnings.

**Comment by sideshowbarker** [comment]
The command-line checker and the network API to the checker currently don’t provide any way to configure which warnings get emitted. The only option is to show all warnings along with errors, or else to show only the errors and show no warnings.

Anyway I think the particular noise problem at https://travis-ci.org/whatwg/encoding/builds/204200335 would be a non-problem if I just made the checker quit emitting the “Text run is not in Unicode Normalization Form C“ warning.

That message used to be an error but years ago I demoted it to being a warning. See https://bugzilla.validator.nu/show_bug.cgi?id=838. The reason I demoted it that the HTML spec does not any normative requirements at all that text being in Unicode Normalization Form C—no “must” requirements and not even any “should” requirement. In fact I think the HTML spec doesn’t mention Unicode Normalization Form C at all.

So the reason I have the checker emitting any message about Unicode Normalization Form C isn’t because of any requirements in the HTML spec but I think instead because of Internationalization best-practice guidance published elsewhere. But in that case it would also be something that the W3C Internationalization Checker https://validator.w3.org/i18n-checker/ is already checking.

And so as far as the HTML checker goes, that warning is a discretionary warning (not required by anything in the HTML spec) and we can use our own discretion to decide it should just be dropped from the HTML checker.

So do think we should just drop it or not? I guess maybe these generated files for the Encoding spec are kind of a special case but I now wonder if maybe they’re not and if other people trying to check documents in other encodings run into this same problem (that is, all errors and warnings about more-serious problems just get drowned out in all the noise from the “Text run is not in Unicode Normalization Form C“ warnings.

**Comment by aphillips** [comment]
That warning is an i18n best practice, but no longer something i18n promotes as a requirement.

That said, it is likely to be specific to Encoding (or to i18n specs: I see it regularly), but it will be rare (and undesirable to ignore) in most normal ones. Might be nice to emit once? Or have an option to suppress it for folks writing specs with lots of Unicode examples?

**Comment by annevk** [comment]
Yeah, I think typically you want to know about non-NFC code points.

**Comment by r12a** [comment]
I certainly get these warnings quite often, and i think always ignore them because there are good reasons for using a non-NFC sequence of content where i do.  Iirc, the i18n checker only looks for non-NFC sequences in class or id names.  Maybe that would be a better check to throw out blow by blow warnings. If there's non-NFC content, i think i'd prefer to just have a single message at the end to say so, but not create a ruckus over it, since it could well be intentional.  

(Btw, this advice is consistent with our article about normalization at https://www.w3.org/International/questions/qa-html-css-normalization)

**Comment by annevk** [comment]
Reopening since the fix didn't work.

@r12a that's probably best suggested at https://github.com/validator/validator/issues/new. Makes sense to have only a single non-NFC message.

**Comment by sideshowbarker** [comment]
https://github.com/whatwg/encoding/pull/109 attempts to re-fix this by changing the curl behavior such that if it hits a timeout, it will automatically retry each request up to 7 times.

FYI I also in the server environment on the server that runs the checker, I also fixed a problem that may have been causing some of the timeouts.

**Comment by sideshowbarker** [comment]
Resolved by https://github.com/whatwg/encoding/commit/8785c3ffe476c1413bf71c1b16f4eecc916e0bc7
